services:
  whatsappbot:
    build: .
    container_name: whatsappbot_container
    shm_size: '2gb'
    ports:
      - "5000:5000"  # [Puerto local]:[Puerto contenedor]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always